/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v2gCommunication.client;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import v2gCommunication.client.ui.*;

/**
 * Class Client main API.
 * 
 * This class builds the GUI for the UI- for the client.
 * 
 * The UI generally consists of a JTabbedPane. Panels including content are 
 * added acoording to userrights of the user logged in. 
 * 
 * To achieve this, the JTabbedPane, as well as the panels with the user 
 * functions are passed to an Instance of {@code ServerConnection} which holds 
 * all logic of the client software.
 * 
 * @author Alexander Forell
 */
public class ClientMainAPI extends javax.swing.JFrame {
    private String userName;
    private String password;
    
    /**
     * Creates new form ClientMainAPI
     */
    public ClientMainAPI() {
        //Autogenerated code by GUI-Builder. 
        initComponents();
        // Sets Icon of API.
        setIcon();
        /**
         * Create Instance of TextAreaOutputStreamm, to output logging 
         * information in the UI. 
         */
        TextAreaOutputStream tout = new TextAreaOutputStream(this.jTextAreaLog, "Log");
        // Redirect System.out
        System.setOut(new PrintStream(tout));
        /**
         * Initialize panels with client functions
         */
        dataAccess = new v2gCommunication.client.ui.DataAccess();
        panelUserManagement = new v2gCommunication.client.ui.PanelUserManagement();
        panelVehicleManagement = new v2gCommunication.client.ui.PanelVehicleManagement();
        panelDataRequest = new v2gCommunication.client.ui.DataRequest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStatus = new javax.swing.JLabel();
        jLabelLoginInfo = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPaneMainContent = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jMenuBarMainMenu = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemLogon = new javax.swing.JMenuItem();
        jMenuItemLogoff = new javax.swing.JMenuItem();
        jSeparatorFileMenu = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("V2X Client");

        jLabelStatus.setText("Status:");

        jLabelLoginInfo.setText("Not Connected");

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTabbedPaneMainContent.setMinimumSize(new java.awt.Dimension(5, 100));
        jSplitPane1.setTopComponent(jTabbedPaneMainContent);

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jTextAreaLog.setRows(5);
        jTextAreaLog.setMaximumSize(new java.awt.Dimension(124, 74));
        jScrollPane1.setViewportView(jTextAreaLog);
        jTextAreaLog.getAccessibleContext().setAccessibleDescription("");

        jSplitPane1.setRightComponent(jScrollPane1);

        jMenuFile.setMnemonic('F');
        jMenuFile.setText("File");

        jMenuItemLogon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLogon.setMnemonic('i');
        jMenuItemLogon.setText("Login");
        jMenuItemLogon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogonActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLogon);

        jMenuItemLogoff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLogoff.setMnemonic('o');
        jMenuItemLogoff.setText("Logout");
        jMenuItemLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoffActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLogoff);
        jMenuFile.add(jSeparatorFileMenu);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemExit.setMnemonic('x');
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBarMainMenu.add(jMenuFile);

        setJMenuBar(jMenuBarMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(773, Short.MAX_VALUE)
                .addComponent(jLabelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLoginInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabelLoginInfo)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Reaction to click on Logon
     * 
     * This mehtod shows the LoginDialog, and evaluates the results coming 
     * back from the login dialog.
     * 
     * It hands over a reference to the JTabbedPane with the main content and
     * the panel with the user functions to the ServerConnection instance. It 
     * calls the {@code startSession} to logon to the server, subsequently the
     * methods {@code getUsers(), getVehcicles() and getUserRights()} in order
     * to initialize the components.
     * 
     * @param evt 
     */                                   
    private void jMenuItemLogonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogonActionPerformed
        // Load Login Dialog.
        LoginDialog loginDialog = new LoginDialog(this, true);
        loginDialog.setVisible(true);
        if(loginDialog.loginDataEntered()){
            // Get entered username and password.
            userName = loginDialog.getUserName();
            password = loginDialog.getPassword();
            try {
                // Transfer reference of components to class ServerConnection
                sc.setJTabbedPaneMainContent(jTabbedPaneMainContent);
                sc.setDataAccess(dataAccess);
                sc.setDataRequest(panelDataRequest);
                sc.setPanelUserManagement(panelUserManagement);
                sc.setPanelVehicleManagement(panelVehicleManagement);
                
                //StartSession and download content of components
                sc.startSession(userName, password);
                sc.getUsers();
                sc.getVehicles();
                // Get Userrights
                sc.getUserRights(userName);
            } catch (IOException | ConnectionAlreadyEstablishedException ex) {
                Logger.getLogger(ClientMainAPI.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jLabelLoginInfo.setText("Connected");
        }
        // close login dialog.
        loginDialog.dispose();
    }//GEN-LAST:event_jMenuItemLogonActionPerformed
    /**
     * Reaction to click on Logoff
     * 
     * Closes session, and removes all panels from the JTabbedPanel
     * 
     * @param evt 
     */
    private void jMenuItemLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoffActionPerformed
        // TODO add your handling code here:
        sc.closeSession();
        this.jLabelLoginInfo.setText("Not Connected");
        jTabbedPaneMainContent.remove(panelUserManagement);
        jTabbedPaneMainContent.remove(panelVehicleManagement);
        jTabbedPaneMainContent.remove(panelDataRequest);
        jTabbedPaneMainContent.remove(dataAccess);
        
    }//GEN-LAST:event_jMenuItemLogoffActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // Add code to proerly log out:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel( javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientMainAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientMainAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientMainAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientMainAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientMainAPI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLoginInfo;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JMenuBar jMenuBarMainMenu;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogoff;
    private javax.swing.JMenuItem jMenuItemLogon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparatorFileMenu;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPaneMainContent;
    private javax.swing.JTextArea jTextAreaLog;
    // End of variables declaration//GEN-END:variables

    
    // private Variables for dynamically added componentes
    private v2gCommunication.client.ui.DataAccess dataAccess;
    private v2gCommunication.client.ui.PanelUserManagement panelUserManagement;
    private v2gCommunication.client.ui.PanelVehicleManagement panelVehicleManagement;
    private v2gCommunication.client.ui.DataRequest panelDataRequest;
    private ServerConnection sc = ServerConnection.getInstance();
    

    
    // End of vairbles declaration 
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/v2gCommunication/client/icons/mainlogo_small.png")));
    }
}
