/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v2gCommunication.client.ui;

import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.ListModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import v2gCommunication.client.ServerConnection;

/**
 *
 * @author alexander
 */
public class DataRequest extends javax.swing.JPanel {
    private ServerConnection sc;
    /**
     * Creates new form VehicleAcess
     */
    public DataRequest() {
        initComponents();
        sc = ServerConnection.getInstance();
        sc.setJListVehiclesDataAccess(jListVehicles);
        
        NumberFormat nfItt = NumberFormat.getIntegerInstance(); // Specify specific format here.
        NumberFormatter nffItt = new NumberFormatter(nfItt);
        nffItt.setMinimum(-1);
        DefaultFormatterFactory factoryItt = new DefaultFormatterFactory(nffItt);
        this.jFormattedTextFieldIterationsBroadcast.setFormatterFactory(factoryItt);
        this.jFormattedTextFieldIterationsVehicle.setFormatterFactory(factoryItt);
        
        NumberFormat nfInt = NumberFormat.getIntegerInstance(); // Specify specific format here.
        NumberFormatter nffInt = new NumberFormatter(nfInt);
        nffInt.setMinimum(1);
        DefaultFormatterFactory factoryInt = new DefaultFormatterFactory(nffInt);
        this.jFormattedTextFieldIntervalBroadcast.setFormatterFactory(factoryInt);
        this.jFormattedTextFieldIntervalVehicle.setFormatterFactory(factoryInt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jSplitPaneVehickeAccess = new javax.swing.JSplitPane();
        jPanelVehicleList = new javax.swing.JPanel();
        jLabelVehicleList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListVehicles = new javax.swing.JList();
        jPanelVehicleData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelVehname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelVehicleStatus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelDataTransmitted = new javax.swing.JLabel();
        jLabelDataReceived = new javax.swing.JLabel();
        jButtonRefreshStatus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFunctionNameVehicle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldIntervalVehicle = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldIterationsVehicle = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelVehname1 = new javax.swing.JLabel();
        jButtonSendRequest = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelVehname2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldFunctionNameBroadcast = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jFormattedTextFieldIntervalBroadcast = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextFieldIterationsBroadcast = new javax.swing.JFormattedTextField();
        jButtonSendBroadcast = new javax.swing.JButton();

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Send Request to vehicle:");

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/v2gCommunication/client/icons/Cars3.png"))); // NOI18N

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitle.setText("Data Request / Vehicle Status");

        jSplitPaneVehickeAccess.setDividerLocation(150);

        jLabelVehicleList.setText("Vehicles");

        jListVehicles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListVehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListVehiclesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListVehicles);

        javax.swing.GroupLayout jPanelVehicleListLayout = new javax.swing.GroupLayout(jPanelVehicleList);
        jPanelVehicleList.setLayout(jPanelVehicleListLayout);
        jPanelVehicleListLayout.setHorizontalGroup(
            jPanelVehicleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelVehicleList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanelVehicleListLayout.setVerticalGroup(
            jPanelVehicleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehicleListLayout.createSequentialGroup()
                .addComponent(jLabelVehicleList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
        );

        jSplitPaneVehickeAccess.setLeftComponent(jPanelVehicleList);

        jLabel1.setText("Vehicle:");

        jLabelVehname.setText("-");

        jLabel2.setText("Status:");

        jLabelVehicleStatus.setText("offline");

        jLabel3.setText("Data transmitted:");

        jLabel4.setText("Data received:");

        jLabelDataTransmitted.setText("0 bytes");

        jLabelDataReceived.setText("0 bytes");

        jButtonRefreshStatus.setText("Refresh");

        jLabel5.setText("Request Function:");

        jLabel6.setText("Interval:");

        jLabel7.setText("Iterations:");

        jLabel8.setText("Vehicle:");

        jLabelVehname1.setText("-");

        jButtonSendRequest.setText("Send");
        jButtonSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendRequestActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Status overview:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Send request to vehicle:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Broadcast request to all vehicles:");

        jLabel13.setText("Vehicle:");

        jLabelVehname2.setText("all");

        jLabel14.setText("Request Function:");

        jLabel15.setText("Interval:");

        jLabel16.setText("Iterations:");

        jFormattedTextFieldIterationsBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldIterationsBroadcastActionPerformed(evt);
            }
        });

        jButtonSendBroadcast.setText("Send");
        jButtonSendBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendBroadcastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVehicleDataLayout = new javax.swing.GroupLayout(jPanelVehicleData);
        jPanelVehicleData.setLayout(jPanelVehicleDataLayout);
        jPanelVehicleDataLayout.setHorizontalGroup(
            jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                        .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVehname)
                            .addComponent(jLabelVehicleStatus)
                            .addComponent(jLabelDataTransmitted)
                            .addComponent(jLabelDataReceived))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRefreshStatus))
                    .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                        .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFormattedTextFieldIterationsVehicle)
                            .addComponent(jFormattedTextFieldIntervalVehicle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFunctionNameVehicle, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSendRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                        .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFormattedTextFieldIterationsBroadcast, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldIntervalBroadcast, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFunctionNameBroadcast, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSendBroadcast, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                        .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(57, 57, 57)
                                .addComponent(jLabelVehname1))
                            .addComponent(jLabel12)
                            .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(57, 57, 57)
                                .addComponent(jLabelVehname2)))
                        .addGap(0, 546, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelVehicleDataLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonRefreshStatus, jButtonSendBroadcast, jButtonSendRequest});

        jPanelVehicleDataLayout.setVerticalGroup(
            jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelVehname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelVehicleStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelDataTransmitted))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelDataReceived)
                    .addComponent(jButtonRefreshStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelVehname1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldFunctionNameVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldIntervalVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldIterationsVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSendRequest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabelVehname2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldFunctionNameBroadcast, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jFormattedTextFieldIntervalBroadcast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jFormattedTextFieldIterationsBroadcast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSendBroadcast))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPaneVehickeAccess.setRightComponent(jPanelVehicleData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPaneVehickeAccess)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTitle)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPaneVehickeAccess))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldIterationsBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldIterationsBroadcastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldIterationsBroadcastActionPerformed

    private void jListVehiclesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListVehiclesMouseClicked
        this.jLabelVehname.setText((String)this.jListVehicles.getSelectedValue());
        this.jLabelVehname1.setText((String)this.jListVehicles.getSelectedValue());
    }//GEN-LAST:event_jListVehiclesMouseClicked

    private void jButtonSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendRequestActionPerformed
        if (this.jListVehicles.getSelectedValue()!=null &&
                this.jTextFieldFunctionNameVehicle.getText()!=null &&
                this.jFormattedTextFieldIntervalVehicle.getText()!=null &&
                this.jFormattedTextFieldIterationsVehicle.getText()!=null){
            ArrayList<String> vehicles = new ArrayList<String>();
            ArrayList<String> functionName = new ArrayList<String>();
            vehicles.add((String)this.jListVehicles.getSelectedValue());
            functionName.add(this.jTextFieldFunctionNameVehicle.getText());
            int iterations = (int) this.jFormattedTextFieldIterationsVehicle.getValue();
            int intervall = (int) this.jFormattedTextFieldIntervalVehicle.getValue();
            sc.initiateRequest(vehicles, functionName, intervall, iterations);
        }
    }//GEN-LAST:event_jButtonSendRequestActionPerformed

    private void jButtonSendBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendBroadcastActionPerformed
        if (this.jTextFieldFunctionNameBroadcast.getText()!=null &&
                this.jFormattedTextFieldIntervalBroadcast.getText()!=null &&
                this.jFormattedTextFieldIterationsBroadcast.getText()!=null){
            ListModel listModel = this.jListVehicles.getModel();
            ArrayList<String> vehicles = new ArrayList<String>();
            for (int i=0;i<listModel.getSize();i++){
                vehicles.add((String)listModel.getElementAt(i));
            }
            ArrayList<String> functionName = new ArrayList<String>();
            functionName.add(this.jTextFieldFunctionNameBroadcast.getText());
            int iterations = (int)this.jFormattedTextFieldIterationsBroadcast.getValue();
            int intervall = (int)this.jFormattedTextFieldIntervalBroadcast.getValue();
            sc.initiateRequest(vehicles, functionName, intervall, iterations);
        }
    }//GEN-LAST:event_jButtonSendBroadcastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRefreshStatus;
    private javax.swing.JButton jButtonSendBroadcast;
    private javax.swing.JButton jButtonSendRequest;
    private javax.swing.JFormattedTextField jFormattedTextFieldIntervalBroadcast;
    private javax.swing.JFormattedTextField jFormattedTextFieldIntervalVehicle;
    private javax.swing.JFormattedTextField jFormattedTextFieldIterationsBroadcast;
    private javax.swing.JFormattedTextField jFormattedTextFieldIterationsVehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDataReceived;
    private javax.swing.JLabel jLabelDataTransmitted;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelVehicleList;
    private javax.swing.JLabel jLabelVehicleStatus;
    private javax.swing.JLabel jLabelVehname;
    private javax.swing.JLabel jLabelVehname1;
    private javax.swing.JLabel jLabelVehname2;
    private javax.swing.JList jListVehicles;
    private javax.swing.JPanel jPanelVehicleData;
    private javax.swing.JPanel jPanelVehicleList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPaneVehickeAccess;
    private javax.swing.JTextField jTextFieldFunctionNameBroadcast;
    private javax.swing.JTextField jTextFieldFunctionNameVehicle;
    // End of variables declaration//GEN-END:variables
}
