/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v2gCommunication.client.ui;

import java.awt.FileDialog;
import java.awt.Frame;
import java.util.ArrayList;
import v2gCommunication.client.ServerConnection;

/**
 *
 * @author alexander
 */
public class DataAccess extends javax.swing.JPanel {
    private ServerConnection sc;
    /**
     * Creates new form VehicleAccess
     * gets an instance of {@code ServerConnection} and adds the components.
     * 
     */
    public DataAccess() {
        initComponents();
        sc = ServerConnection.getInstance();
        sc.setJListVehiclesRequestManagement(jListVehicles);
        sc.setJListVehiclesFunctions(jListFunctions);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIcon = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jSplitPaneVehickeAccess = new javax.swing.JSplitPane();
        jPanelVehicleList = new javax.swing.JPanel();
        jLabelVehicleList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListVehicles = new javax.swing.JList();
        jPanelVehicleData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListFunctions = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/v2gCommunication/client/icons/Cars3.png"))); // NOI18N

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitle.setText("Data Access");

        jSplitPaneVehickeAccess.setDividerLocation(150);

        jLabelVehicleList.setText("Vehicles");

        jListVehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListVehiclesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListVehicles);

        javax.swing.GroupLayout jPanelVehicleListLayout = new javax.swing.GroupLayout(jPanelVehicleList);
        jPanelVehicleList.setLayout(jPanelVehicleListLayout);
        jPanelVehicleListLayout.setHorizontalGroup(
            jPanelVehicleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelVehicleList, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanelVehicleListLayout.setVerticalGroup(
            jPanelVehicleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehicleListLayout.createSequentialGroup()
                .addComponent(jLabelVehicleList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
        );

        jSplitPaneVehickeAccess.setLeftComponent(jPanelVehicleList);

        jLabel1.setText("Vehicle: ");

        jLabel2.setText("-");

        jLabel3.setText("Functions: ");

        jScrollPane2.setViewportView(jListFunctions);

        jButton1.setText("Download data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVehicleDataLayout = new javax.swing.GroupLayout(jPanelVehicleData);
        jPanelVehicleData.setLayout(jPanelVehicleDataLayout);
        jPanelVehicleDataLayout.setHorizontalGroup(
            jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVehicleDataLayout.createSequentialGroup()
                        .addGap(0, 477, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanelVehicleDataLayout.setVerticalGroup(
            jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehicleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVehicleDataLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 251, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jSplitPaneVehickeAccess.setRightComponent(jPanelVehicleData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSplitPaneVehickeAccess)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPaneVehickeAccess))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * Calls {@code ServerConnection.getVehicleFunctions} in order to see what kind of data
     * is available on the database
     * 
     * @param evt 
     */
    private void jListVehiclesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListVehiclesMouseClicked
        ArrayList<String> vehnames = new ArrayList<String>();
        int[] selectedIx = this.jListVehicles.getSelectedIndices();

        for (int i = 0; i < selectedIx.length; i++) {
            vehnames.add((String) jListVehicles.getModel().getElementAt(selectedIx[i]));
        }
        sc.getVehicleFunctions(vehnames);
    }//GEN-LAST:event_jListVehiclesMouseClicked
    
    /**
     * Calls {@code ServerConnection.downloadData} to download the information
     * from the database
     * 
     * To select the storage directory a file dialog is created and shown.
     * 
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FileDialog fd = new FileDialog(new Frame(), "Store File", FileDialog.SAVE);
        fd.setVisible(true);
        ArrayList<String> vehnames = new ArrayList<String>();
        int[] selectedIxVh = this.jListVehicles.getSelectedIndices();

        for (int i = 0; i < selectedIxVh.length; i++) {
            vehnames.add((String) jListVehicles.getModel().getElementAt(selectedIxVh[i]));
        }
        ArrayList<String> functions = new ArrayList<String>();
        int[] selectedIxFu = this.jListFunctions.getSelectedIndices();

        for (int i = 0; i < selectedIxFu.length; i++) {
            functions.add((String) jListFunctions.getModel().getElementAt(selectedIxFu[i]));
        }
        String fn = fd.getDirectory()+fd.getFile();
        sc.downloadData(vehnames, functions, fn);
        
        fd.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelVehicleList;
    private javax.swing.JList jListFunctions;
    private javax.swing.JList jListVehicles;
    private javax.swing.JPanel jPanelVehicleData;
    private javax.swing.JPanel jPanelVehicleList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPaneVehickeAccess;
    // End of variables declaration//GEN-END:variables
}
