/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v2gCommunication.client.ui;

import v2gCommunication.client.ServerConnection;


/**
 *
 * @author alexander
 */
public class PanelUserManagement extends javax.swing.JPanel {
    
    ServerConnection sc;
    /**
     * Creates new form NewUserManagement
     */
    public PanelUserManagement() {
        initComponents();
        this.sc = ServerConnection.getInstance();
        sc.setJListUsers(jListUsers);
        jTabbedPaneAccountData.add(panelUserData1,"User data");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUserHeading = new javax.swing.JLabel();
        jLabelUserIcon = new javax.swing.JLabel();
        jButtonAddAccount = new javax.swing.JButton();
        jButtonDeleteAccount = new javax.swing.JButton();
        jButtonAlppy = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelUserList = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUsers = new javax.swing.JList();
        jTabbedPaneAccountData = new javax.swing.JTabbedPane();

        jLabelUserHeading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUserHeading.setText("Users and Privileges");

        jLabelUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/v2gCommunication/client/icons/user3.png"))); // NOI18N

        jButtonAddAccount.setText("Add Account");
        jButtonAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAccountActionPerformed(evt);
            }
        });

        jButtonDeleteAccount.setText("Delete");
        jButtonDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAccountActionPerformed(evt);
            }
        });

        jButtonAlppy.setText("Apply");
        jButtonAlppy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlppyActionPerformed(evt);
            }
        });

        jSplitPane1.setDividerLocation(150);

        jLabel1.setText("User Accounts");

        jListUsers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item1", "Item2", "Item3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListUsers);
        jListUsers.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanelUserListLayout = new javax.swing.GroupLayout(jPanelUserList);
        jPanelUserList.setLayout(jPanelUserListLayout);
        jPanelUserListLayout.setHorizontalGroup(
            jPanelUserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanelUserListLayout.setVerticalGroup(
            jPanelUserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserListLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanelUserList);
        jSplitPane1.setRightComponent(jTabbedPaneAccountData);
        jTabbedPaneAccountData.getAccessibleContext().setAccessibleName("User ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAlppy, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelUserIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUserHeading)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUserHeading)
                    .addComponent(jLabelUserIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddAccount)
                    .addComponent(jButtonDeleteAccount)
                    .addComponent(jButtonAlppy)))
        );

        getAccessibleContext().setAccessibleName("User Management");
        getAccessibleContext().setAccessibleDescription("User Management");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlppyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlppyActionPerformed
        String username = this.panelUserData1.getUserName();
        String password = this.panelUserData1.getPasswort();
        boolean canModifyUsers = this.panelUserData1.getCanModfiyUsers();
        boolean canModifyVehicles = this.panelUserData1.getCanModfiyVehicles();
        boolean canSendRequest = this.panelUserData1.getCanSendRequest();
        if ((username != null) && (password!=null)){
            ServerConnection sc = ServerConnection.getInstance();
            sc.changePassword(username, password);
        }
        if (username != null){
            sc.updateUserRights(username, canModifyUsers, canModifyVehicles, canSendRequest);
        }
    }//GEN-LAST:event_jButtonAlppyActionPerformed

    private void jButtonAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAccountActionPerformed
        String username = this.panelUserData1.getUserName();
        String password = this.panelUserData1.getPasswort();
        boolean canModifyUsers = this.panelUserData1.getCanModfiyUsers();
        boolean canModifyVehicles = this.panelUserData1.getCanModfiyVehicles();
        boolean canSendRequest = this.panelUserData1.getCanSendRequest();
        if ((username != null) && (password!=null)){
            ServerConnection sc = ServerConnection.getInstance();
            sc.createUser(username, password, canModifyUsers, 
                    canModifyVehicles, canSendRequest);
        }    
    }//GEN-LAST:event_jButtonAddAccountActionPerformed

    private void jButtonDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAccountActionPerformed
        String username = (String) this.jListUsers.getSelectedValue();
        if (username != null){
            sc.deleteUser(username);
        }
    }//GEN-LAST:event_jButtonDeleteAccountActionPerformed

    private void jListUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListUsersMouseClicked
        String username = (String) this.jListUsers.getSelectedValue();
        if (username != null){
            sc.getUserRights(username);
        }
    }//GEN-LAST:event_jListUsersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAccount;
    private javax.swing.JButton jButtonAlppy;
    private javax.swing.JButton jButtonDeleteAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUserHeading;
    private javax.swing.JLabel jLabelUserIcon;
    private javax.swing.JList jListUsers;
    private javax.swing.JPanel jPanelUserList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPaneAccountData;
    // End of variables declaration//GEN-END:variables
    private PanelUserData panelUserData1 = new PanelUserData();
}

